### ISSUE TITLE
Error : module 'tensorflow' has no attribute 'Dimension'

### ISSUE THREAD

**Issue by matrob67** [cedricoeldorf/ConditionalStyleGAN#3]
When running the pretrained_example.py file, I have

Traceback (most recent call last):
  File "C:/Users/CAO/Desktop/ConditionalStyleGAN/pretrained_example.py", line 15, in <module>
    import dnnlib.tflib as tflib
  File "C:\Users\CAO\Desktop\ConditionalStyleGAN\dnnlib\tflib\__init__.py", line 8, in <module>
    from . import autosummary
  File "C:\Users\CAO\Desktop\ConditionalStyleGAN\dnnlib\tflib\autosummary.py", line 31, in <module>
    from . import tfutil
  File "C:\Users\CAO\Desktop\ConditionalStyleGAN\dnnlib\tflib\tfutil.py", line 34, in <module>
    def shape_to_list(shape: Iterable[tf.Dimension]) -> List[Union[int, None]]:
AttributeError: module 'tensorflow' has no attribute 'Dimension'

**Comment by adamandworking** [comment]
I guess it is because your TensorFlow version is not correct. Try 1.14.0 see whether it fits.

**Comment by ldaumail** [comment]
I am having the same issue. I also tried with TensorFlow 1.14.0, but it doesn't work, so I went back to using TensorFlow 2.1.0, but it still doesn't work. 
I am trying to run it from Wing Pro 7 (version 7.1.3.2 (rev 3600c9873c6f))
And I use a MacOS Catalina version 10.15.3
Processor: 2.3 GHz 8-Core Intel Core i9
Memory: 16 GB 2400 MHz DDR4
Graphics: Radeon Pro 560X 4 GB
Intel UHD Graphics 630 1536 MB

I can't figure out what is wrong with /dnnlib/tflib/tfutil.py

Thanks in advance for your help!

**Comment by ashutoshsoni891** [comment]
Let me share how I solved this issue :

instead of  importing : import dnnlib.tflib as tflib
use this  : import dnnlib.tflib as tfl

Idea is  , inplace of tflib you can use any name except tflib

**Comment by Rams901** [comment]
tf.Dimension is deprecated. Can be found using tf.compat.v1.Dimension

**Comment by ashutoshsoni891** [comment]
> tf.Dimension is deprecated. Can be found using tf.compat.v1.Dimension

@Rams901  don't vote blindly until know the things

**Comment by jamezening** [comment]
> Let me share how I solved this issue :
> 
> instead of importing : import dnnlib.tflib as tflib
> use this : import dnnlib.tflib as tfl
> 
> Idea is , inplace of tflib you can use any name except tflib
This didn't work for me either.

I am getting the following error: 
> AttributeError: module 'tensorflow' has no attribute 'Dimension'

Will try with a different version of `tensorflow`, namely 1.14.0.

Meanwhile, has anyone had any luck resolving this issue?

**Comment by prateekralhan** [comment]
Do : pip install tensorflow==1.15.2

It will work :smile:

**Comment by ankushbanik1** [comment]
> 
> 
> Do : pip install tensorflow==1.15.2
> 
> It will work 😄

yes it worked thanks

**Comment by albusdemens** [comment]
For posterity: I fixed it using `conda install tensorflow-gpu==1.9.0`.

**Comment by nehalgajraj** [comment]
try using tensorflow version 1.10.0 
(!pip install tensorflow==1.10.0)

worked for me on colab.research.google.com

**Comment by dinuka125** [comment]
> I guess it is because your TensorFlow version is not correct. Try 1.14.0 see whether it fits.

This worked for me in Google Colab, Thanks (!pip install tensorflow==1.14.0)

**Comment by portvs** [comment]
tensorflow versions 1.14.0 ,1.15.2 are not supported now.

**Comment by Wuyu-love** [comment]
> tensorflow versions 1.14.0 ,1.15.2 are not supported now.

So how to solve now? any ideas?

**Comment by Miao-kristoff** [comment]
> tensorflow versions 1.14.0 ,1.15.2 are not supported now.

Any ideas to solve it for now?

**Comment by emnab** [comment]
tensorflow versions 1.14.0 ,1.15.2 are not supported now
